# Generated by Django 4.0.2 on 2022-03-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate_profile',
            name='my_balance',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
