# Generated by Django 4.0.2 on 2022-03-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_affiliate_profile_my_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate_profile',
            old_name='my_balance',
            new_name='withdrawn',
        ),
    ]
