# Generated by Django 4.0.2 on 2022-03-07 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_rename_my_balance_affiliate_profile_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
