# Generated by Django 4.0.2 on 2022-02-28 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('home_slider', models.CharField(blank=True, choices=[('category1', 'category1'), ('category2', 'category2'), ('category3', 'category3')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_percentage', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Governorates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.TextField(max_length=2800)),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=2000)),
                ('price', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('main_image', models.ImageField(upload_to='main_image/%y/%m/%d')),
                ('discount_percentage', models.CharField(blank=True, max_length=5, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('all_image', models.ManyToManyField(blank=True, null=True, to='shop.All_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('number1', models.CharField(max_length=11)),
                ('number2', models.CharField(blank=True, max_length=11, null=True)),
                ('governorate', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=1000)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('coupon', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_discount', models.CharField(blank=True, max_length=5, null=True)),
                ('total', models.CharField(max_length=10)),
                ('shipping', models.CharField(max_length=10)),
                ('payable', models.CharField(max_length=20)),
                ('items', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('جاري تاكيد الطلب', 'جاري تاكيد الطلب'), ('جاري تجهيز الطلب', 'جاري تجهيز الطلب'), ('قيد التوصيل', 'قيد التوصيل'), ('تم التوصيل', 'تم التوصيل'), ('تعليق التوصيل', 'تعليق التوصيل'), ('تم إلغاء أو رفض الطلب', 'تم إلغاء أو رفض الطلب')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Address_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('number1', models.CharField(max_length=20)),
                ('number2', models.CharField(blank=True, max_length=20, null=True)),
                ('governorate', models.CharField(choices=[('القاهرة', 'القاهرة'), ('الجيزة', 'الجيزة'), ('الإسكندرية', 'الإسكندرية'), ('الإسماعيلية', 'الإسماعيلية'), ('بور سعيد', 'بور سعيد'), ('السويس', 'السويس'), ('أسوان', 'أسوان'), ('أسيوط', 'أسيوط'), ('الأقصر', 'الأقصر'), ('البحر الأحمر', 'البحر الأحمر'), ('البحيرة', 'البحيرة'), ('بنى سويف', 'بنى سويف'), ('جنوب سيناء', 'جنوب سيناء'), ('الدقهلية', 'الدقهلية'), ('دمياط', 'دمياط'), ('سوهاج', 'سوهاج'), ('الشرقية', 'الشرقية'), ('سينا', 'سينا'), ('الغربية', 'الغربية'), ('الفيوم', 'الفيوم'), ('القليوبية', 'القليوبية'), ('قنا', 'قنا'), ('كفر الشيخ', 'كفر الشيخ'), ('مطروح', 'مطروح'), ('المنوفية', 'المنوفية'), ('المنيا', 'المنيا'), ('الوادى الجديد', 'الوادى الجديد')], max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=1000)),
                ('active', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('shipping', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
