# Generated by Django 4.0.2 on 2022-03-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_earn',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='coupon_discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True),
        ),
    ]
