# Generated by Django 4.0.2 on 2022-03-05 14:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_affiliate_earn_product_coupon_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/%y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
