# Generated by Django 4.0.2 on 2022-03-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_coupon_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='earn',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
