# Generated by Django 4.0.2 on 2022-03-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_affiliate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='affiliate_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
