# Generated by Django 4.0.2 on 2022-03-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_affiliate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
