# Generated by Django 4.0.2 on 2022-03-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cart_affiliate_code_alter_order_affiliate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='media/main_image/%y/%m/%d'),
        ),
    ]
