# Generated by Django 4.0.2 on 2022-03-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_all_image_image_alter_features_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_grid_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/img/%y/%m/%d')),
            ],
        ),
    ]
